Repository ilios/common, pull requests merged in 2018-10, with the labels that each got.

#313 switched back to official release for pikaday.
  package.json
  yarn.lock
Labels: in progress

#315 restore objective competency manager clickability
  addon/templates/components/objective-manage-competency.hbs
Labels: in progress, ready for review

#314 Update ember cli 3.4.3
  package.json
  yarn.lock
Labels: in progress

#317 Float dependencies
  package.json
  yarn.lock
Labels: in progress, ready for review

#320 moved relevant lang strings from frontend.
  addon/locales/en/translations.js
  addon/locales/es/translations.js
  addon/locales/fr/translations.js
Labels: in progress

#321 wired up omitted component styles.
  app/styles/ilios-common/components.scss
Labels: in progress

#322 Move publish all mixin to the controller
  addon/components/publish-all-sessions.js
  addon/mixins/course/publish-all-controller.js
  addon/mixins/course/publishall-route.js
  tests/unit/mixins/course/publish-all-controller-test.js
  tests/unit/mixins/course/publishall-route-test.js
Labels: in progress

#326 Update linter and fix errors
  addon/templates/components/big-text.hbs
  addon/templates/components/click-choice-buttons.hbs
  addon/templates/components/course-leadership-expanded.hbs
  addon/templates/components/course-objective-list-item.hbs
  addon/templates/components/course-rollover.hbs
  addon/templates/components/dashboard-calendar.hbs
  addon/templates/components/dashboard-view-picker.hbs
  addon/templates/components/detail-competencies.hbs
  addon/templates/components/detail-objectives.hbs
  addon/templates/components/detail-taxonomies.hbs
  addon/templates/components/editable-field.hbs
  addon/templates/components/ilios-calendar-month.hbs
  addon/templates/components/ilios-calendar-multiday-event.hbs
  addon/templates/components/ilios-calendar-week.hbs
  addon/templates/components/ilios-calendar.hbs
  addon/templates/components/ilios-course-details.hbs
  addon/templates/components/leadership-collapsed.hbs
  addon/templates/components/learningmaterial-manager.hbs
  addon/templates/components/learningmaterial-search.hbs
  addon/templates/components/mesh-manager.hbs
  addon/templates/components/new-objective.hbs
  addon/templates/components/offering-form.hbs
  addon/templates/components/offering-manager.hbs
  addon/templates/components/publish-all-sessions.hbs
  addon/templates/components/selected-term-tree.hbs
  addon/templates/components/session-copy.hbs
  addon/templates/components/session-leadership-expanded.hbs
  addon/templates/components/session-objective-list-item.hbs
  addon/templates/components/session-objective-manager.hbs
  addon/templates/components/single-event-objective-list.hbs
  addon/templates/components/toggle-wide.hbs
  addon/templates/components/user-search.hbs
  addon/templates/components/week-glance.hbs
  package.json
  yarn.lock
Labels: in progress, ready for review

#341 Update ember data 3.5
  addon/models/competency.js
  addon/models/learner-group.js
  addon/models/session.js
  package.json
  tests/unit/models/competency-test.js
  tests/unit/models/curriculum-inventory-report-test.js
  tests/unit/models/learner-group-test.js
  tests/unit/models/program-test.js
  tests/unit/models/session-test.js
  tests/unit/models/user-test.js
  yarn.lock
Labels: in progress, ready for review

#335 Move tests and validator from frontend
  addon/helpers/count-related.js
  addon/helpers/not-in.js
  addon/validators/html-presence.js
  app/helpers/count-related.js
  app/helpers/not-in.js
  app/validators/html-presence.js
  ember-cli-build.js
  index.js
  package.json
  tests/integration/components/click-choice-button-test.js
  tests/integration/components/collapsed-objectives-test.js
  tests/integration/components/course-leadership-expanded-test.js
  tests/integration/components/course-loading-test.js
  tests/integration/components/course-materials-test.js
  tests/integration/components/course-objective-list-item-test.js
  tests/integration/components/course-sessions-test.js
  tests/integration/components/course-summary-header-test.js
  tests/integration/components/detail-cohort-list-test.js
  tests/integration/components/detail-learnergroups-list-test.js
  tests/integration/components/detail-terms-list-item-test.js
  tests/integration/components/detail-terms-list-test.js
  tests/integration/components/expand-collapse-button-test.js
  tests/integration/components/leadership-collapsed-test.js
  tests/integration/components/leadership-list-test.js
  tests/integration/components/learnergroup-tree-test.js
  tests/integration/components/learningmaterial-search-test.js
  tests/integration/components/new-objective-test.js
  tests/integration/components/new-offering-test.js
  tests/integration/components/progress-bar-test.js
  tests/integration/components/publish-all-sessions-test.js
  tests/integration/components/publish-menu-test.js
  tests/integration/components/search-box-test.js
  tests/integration/components/selectable-terms-list-item-test.js
  tests/integration/components/selectable-terms-list-test.js
  tests/integration/components/session-leadership-expanded-test.js
  tests/integration/components/session-objective-list-item-test.js
  tests/integration/components/session-objective-list-test.js
  tests/integration/components/sessions-grid-header-test.js
  tests/integration/components/sessions-grid-loading-test.js
  tests/integration/components/sessions-grid-offering-test.js
  tests/integration/components/sessions-grid-test.js
  tests/integration/components/sortable-heading-test.js
  tests/integration/components/sortable-th-test.js
  tests/integration/components/taxonomy-manager-test.js
  tests/integration/components/toggle-yesno-test.js
  tests/integration/components/visualizer-course-instructor-session-type-test.js
  tests/integration/components/visualizer-course-instructor-term-test.js
  tests/integration/components/visualizer-course-instructors-test.js
  tests/integration/components/visualizer-course-objectives-test.js
  tests/integration/components/visualizer-course-session-type-test.js
  tests/integration/components/visualizer-course-session-types-test.js
  tests/integration/components/visualizer-course-term-test.js
  tests/integration/components/visualizer-course-vocabularies-test.js
  tests/integration/components/visualizer-course-vocabulary-test.js
  tests/unit/helpers/count-related-test.js
  tests/unit/helpers/has-many-length-test.js
  tests/unit/helpers/is-in-test.js
  tests/unit/helpers/not-in-test.js
  yarn.lock
Labels: ready for review

#343 clear error message earlier.
  addon/mixins/objective-list-item.js
Labels: in progress

#344 Add missing dependencies and component
  addon/breakpoints.js
  addon/components/removable-row.js
  app/components/removable-row.js
  package.json
  yarn.lock
Labels: in progress, ready for review

#347 moved error lang strings from frontend.
  addon/locales/en/translations.js
  addon/locales/es/translations.js
  addon/locales/fr/translations.js
Labels: in progress, ready for review

#348 removed ember-light-table dependency
  addon/components/detail-learning-materials.js
  addon/components/learning-material-table.js
  addon/templates/components/detail-learning-materials.hbs
  addon/templates/components/learning-material-table.hbs
  app/components/learning-material-table.js
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/learning-material-table.scss
  package.json
  tests/integration/components/detail-learning-materials-test.js
  yarn.lock
Labels: ready for review

#351 Fix the rebuilding of the addon-test-support directory
  index.js
Labels: in progress, ready for review

#350 Remove light table dependencies
  addon/breakpoints.js
  addon/components/removable-row.js
  app/components/removable-row.js
  package.json
  yarn.lock
Labels: in progress, ready for review

#353 Skip canary tests
  .travis.yml
Labels: in progress

#354 Include test files in package
  index.js
  package.json
Labels: in progress

#352 Default ember-concurrency to debug mode in development
  tests/dummy/config/environment.js
Labels: in progress

#357 Conditional link back to courses
  addon/helpers/has-route.js
  addon/templates/components/course-loading.hbs
  addon/templates/components/ilios-course-details.hbs
  app/helpers/has-route.js
  tests/integration/components/course-loading-test.js
  tests/integration/helpers/has-route-test.js
Labels: in progress, ready for review

#358 Move component tests
  package.json
  tests/integration/components/collapsed-competencies-test.js
  tests/integration/components/collapsed-learnergroups-test.js
  tests/integration/components/course-objective-list-test.js
  tests/integration/components/course-overview-test.js
  tests/integration/components/course-rollover-test.js
  tests/integration/components/html-editor-test.js
  tests/integration/components/leadership-manager-test.js
  tests/integration/components/leadership-search-test.js
  tests/integration/components/learning-materials-sort-manager-test.js
  tests/integration/components/objective-sort-manager-test.js
  tests/integration/components/offering-form-test.js
  tests/integration/components/session-copy-test.js
  tests/integration/components/sessions-grid-offering-table-test.js
  tests/integration/components/user-search-test.js
  tests/integration/components/wait-saving-test.js
  yarn.lock
Labels: in progress, ready for review

#364 ember-i18n to to ember-intl conversion
  addon/components/back-link.js
  addon/components/course-objective-manager.js
  addon/components/course-overview.js
  addon/components/course-sessions.js
  addon/components/dashboard-calendar.js
  addon/components/detail-cohort-list.js
  addon/components/detail-cohort-manager.js
  addon/components/detail-learning-materials.js
  addon/components/detail-mesh.js
  addon/components/detail-objectives.js
  addon/components/detail-taxonomies.js
  addon/components/html-editor.js
  addon/components/ilios-calendar-event.js
  addon/components/instructor-selection-manager.js
  addon/components/leadership-search.js
  addon/components/learnergroup-selection-manager.js
  addon/components/learningmaterial-search.js
  addon/components/mesh-manager.js
  addon/components/session-offerings.js
  addon/components/single-event.js
  addon/components/taxonomy-manager.js
  addon/components/user-search.js
  addon/components/visualizer-course-instructor-session-type.js
  addon/components/visualizer-course-instructor-term.js
  addon/components/visualizer-course-instructors.js
  addon/components/visualizer-course-objectives.js
  addon/components/visualizer-course-session-type.js
  addon/components/visualizer-course-session-types.js
  addon/components/visualizer-course-term.js
  addon/components/visualizer-course-vocabularies.js
  addon/components/visualizer-course-vocabulary.js
  addon/components/week-glance.js
  addon/instance-initializers/load-common-translations.js
  addon/locales/en/translations.js
  addon/locales/es/translations.js
  addon/locales/fr/translations.js
  addon/mixins/publishable.js
  addon/mixins/tooltip-content.js
  app/formats.js
  app/instance-initializers/load-common-translations.js
  config/ember-intl.js
  package.json
  tests/dummy/config/environment.js
  tests/integration/components/learning-materials-sort-manager-test.js
  tests/integration/components/learningmaterial-search-test.js
  tests/integration/components/objective-sort-manager-test.js
  tests/integration/components/toggle-yesno-test.js
  tests/integration/components/wait-saving-test.js
  tests/unit/models/program-test.js
  tests/unit/translations-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
  yarn.lock
Labels: in progress, ready for review

#366 Publish translations with module
  package.json
Labels: in progress, ready for review

#367 moved boolean check component test from frontend.
  tests/unit/components/boolean-check-test.js
Labels: in progress, ready for review

#371 correctly pass arguments to taughtBy lang string
  addon/mixins/tooltip-content.js
  addon/templates/components/ilios-calendar-event.hbs
Labels: in progress

#372 Test event tooltip
  addon/components/ilios-calendar-event.js
  tests/acceptance/dashboard/calendar-test.js
Labels: in progress, ready for review

#373 Don't greenkeeper ember-qunit
  package.json
Labels: in progress

#376 moved lang strings into common.
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: in progress, ready for review
