Repository ilios/common, pull requests merged in 2018-09, with the labels that each got.

#280 Update ilios-jwt authenticator for ESA-token v4
  addon/authenticators/ilios-jwt.js
  yarn.lock
Labels: in progress, ready for review

#281 Make z-index reasonable
  app/styles/ilios-common/mixins/ilios-input.scss
Labels: in progress, ready for review

#285 Re-implement course admin related controllers as mixins
  addon/mixins/course-controller.js
  addon/mixins/course-materials-controller.js
  addon/mixins/course-visualize-instructors-controller.js
  addon/mixins/course/index-controller.js
  addon/mixins/course/rollover-controller.js
  addon/mixins/print-course-controller.js
  addon/mixins/session-controller.js
  addon/mixins/session/copy-controller.js
  addon/mixins/session/index-controller.js
  tests/unit/mixins/course-controller-test.js
  tests/unit/mixins/course-materials-controller-test.js
  tests/unit/mixins/course-visualize-instructors-controller-test.js
  tests/unit/mixins/course/index-controller-test.js
  tests/unit/mixins/course/rollover-controller-test.js
  tests/unit/mixins/print-course-controller-test.js
  tests/unit/mixins/session-controller-test.js
  tests/unit/mixins/session/copy-controller-test.js
  tests/unit/mixins/session/index-controller-test.js
Labels: in progress, ready for review

#288 Update ember-cli-sass
  package.json
  yarn.lock
Labels: in progress

#290 Fix template linting issues
  addon/templates/components/back-link.hbs
  addon/templates/components/big-text.hbs
  addon/templates/components/common-dashboard.hbs
  addon/templates/components/dashboard-agenda.hbs
  addon/templates/components/dashboard-calendar.hbs
  addon/templates/components/dashboard-materials.hbs
  addon/templates/components/dashboard-view-picker.hbs
  addon/templates/components/dashboard-week.hbs
  addon/templates/components/ics-feed.hbs
  addon/templates/components/ilios-calendar-day.hbs
  addon/templates/components/ilios-calendar-event-month.hbs
  addon/templates/components/ilios-calendar-event.hbs
  addon/templates/components/ilios-calendar-month.hbs
  addon/templates/components/ilios-calendar-multiday-event.hbs
  addon/templates/components/ilios-calendar-multiday-events.hbs
  addon/templates/components/ilios-calendar-week.hbs
  addon/templates/components/ilios-calendar.hbs
  addon/templates/components/lm-type-icon.hbs
  addon/templates/components/pulse-loader.hbs
  addon/templates/components/selected-term-tree.hbs
  addon/templates/components/single-event-learningmaterial-list.hbs
  addon/templates/components/single-event-objective-list.hbs
  addon/templates/components/single-event.hbs
  addon/templates/components/timed-release-schedule.hbs
  addon/templates/components/toggle-buttons.hbs
  addon/templates/components/toggle-icons.hbs
  addon/templates/components/toggle-wide.hbs
  addon/templates/components/week-glance.hbs
  addon/templates/components/weekly-events.hbs
  addon/templates/weeklyevents.hbs
Labels: ready for review

#286 Re-implement course admin related routes as mixins
  addon/mixins/course-materials-route.js
  addon/mixins/course-route.js
  addon/mixins/course-visualizations-route.js
  addon/mixins/course-visualize-instructor-route.js
  addon/mixins/course-visualize-instructors-route.js
  addon/mixins/course-visualize-objectives-route.js
  addon/mixins/course-visualize-session-type-route.js
  addon/mixins/course-visualize-session-types-route.js
  addon/mixins/course-visualize-term-route.js
  addon/mixins/course-visualize-vocabularies-route.js
  addon/mixins/course-visualize-vocabulary-route.js
  addon/mixins/course/index-route.js
  addon/mixins/course/publishall-route.js
  addon/mixins/print-course-route.js
  addon/mixins/session-route.js
  addon/mixins/session/copy-route.js
  addon/mixins/session/index-route.js
  tests/unit/mixins/course-materials-route-test.js
  tests/unit/mixins/course-route-test.js
  tests/unit/mixins/course-visualizations-route-test.js
  tests/unit/mixins/course-visualize-instructor-route-test.js
  tests/unit/mixins/course-visualize-instructors-route-test.js
  tests/unit/mixins/course-visualize-objectives-route-test.js
  tests/unit/mixins/course-visualize-session-type-route-test.js
  tests/unit/mixins/course-visualize-session-types-route-test.js
  tests/unit/mixins/course-visualize-term-route-test.js
  tests/unit/mixins/course-visualize-vocabularies-route-test.js
  tests/unit/mixins/course-visualize-vocabulary-route-test.js
  tests/unit/mixins/course/index-route-test.js
  tests/unit/mixins/course/publishall-route-test.js
  tests/unit/mixins/print-course-route-test.js
  tests/unit/mixins/session-route-test.js
  tests/unit/mixins/session/copy-route-test.js
  tests/unit/mixins/session/index-route-test.js
Labels: ready for review

#295 moved serializers from frontend.
  addon/serializers/course.js
  addon/serializers/ilm-session.js
  addon/serializers/learning-material.js
  addon/serializers/offering.js
  addon/serializers/session.js
  app/serializers/course.js
  app/serializers/ilm-session.js
  app/serializers/learning-material.js
  app/serializers/offering.js
  app/serializers/session.js
  tests/unit/serializers/course-test.js
  tests/unit/serializers/ilm-session-test.js
  tests/unit/serializers/learning-material-test.js
  tests/unit/serializers/offering-test.js
  tests/unit/serializers/session-test.js
Labels: in progress

#299 merge() is deprecated, using assign() instead.
  addon/authenticators/ilios-jwt.js
Labels: in progress

#297 indentation fix.
  addon/templates/components/timed-release-schedule.hbs
Labels: ready for review

#301 provide missing component args to tests.
  tests/integration/components/toggle-icons-test.js
Labels: ready for review

#287 Greenkeeper/ember cli 3.4.1
  .eslintignore
  .eslintrc.js
  .npmignore
  .template-lintrc.js
  .travis.yml
  README.md
  addon/locales/en/translations.js
  addon/locales/es/translations.js
  addon/locales/fr/translations.js
  addon/templates/components/big-text.hbs
  addon/templates/components/dashboard-calendar.hbs
  addon/templates/components/ilios-calendar-event-month.hbs
  addon/templates/components/ilios-calendar-event.hbs
  addon/templates/components/ilios-calendar-month.hbs
  addon/templates/components/ilios-calendar-multiday-event.hbs
  addon/templates/components/ilios-calendar-week.hbs
  addon/templates/components/ilios-calendar.hbs
  addon/templates/components/selected-term-tree.hbs
  addon/templates/components/single-event-learningmaterial-list.hbs
  addon/templates/components/single-event-objective-list.hbs
  addon/templates/components/single-event.hbs
  addon/templates/components/toggle-wide.hbs
  addon/templates/components/week-glance.hbs
  config/ember-try.js
  index.js
  package.json
  tests/dummy/app/templates/index.hbs
  tests/dummy/app/templates/login.hbs
  tests/dummy/config/optional-features.json
  yarn.lock
Labels: in progress

#312 fixes various, component migration related, bugs.
  addon/components/sessions-grid-offering-table.js
  addon/components/sessions-grid-offering.js
  addon/components/sessions-grid-offerings-table.js
  app/components/sessions-grid-offerings-table.js
  package.json
  yarn.lock
Labels: in progress
