Repository ilios/common, pull requests merged in 2018-05, with the labels that each got.

#222 Add canUpdateAllCoursesInSchool to permissionCheccker
  addon/services/permission-checker.js
Labels: in progress, ready for review

#224 Fix hasMoreThanOneSchool property in calendar
  addon/components/dashboard-calendar.js
Labels: in progress, ready for review

#225 prevent updating and deletion of locked/archived program years.
  addon/services/permission-checker.js
Labels: in progress

#226 Reload by default
  addon/adapters/ilios.js
Labels: in progress

#229 Remove canCreateCIReportInAnySchool property
  addon/services/current-user.js
Labels: in progress, ready for review

#227 Fix role given to session instructors
  addon/services/current-user.js
Labels: in progress, ready for review

#228 Add PROGRAM_DIRECTOR to school roles
  addon/services/current-user.js
Labels: in progress, ready for review

#230 grants update permissions on instructor groups to school- and program-directors.
  addon/services/permission-matrix.js
Labels: ready for review

#232 Greenkeeper/ember tether 1.0.0 beta.2
  package.json
  yarn.lock
Labels: in progress

#231 Avoid loading unnecessary data
  addon/services/current-user.js
  addon/services/permission-checker.js
  addon/services/permission-matrix.js
Labels: in progress, ready for review

#237 Replace ember-tooltips with ember-attachment
  addon/templates/components/ilios-calendar-event-month.hbs
  addon/templates/components/ilios-calendar-event.hbs
  package.json
  yarn.lock
Labels: in progress

#239 Left alight event tooltip content
  addon/templates/components/ilios-calendar-event-month.hbs
  addon/templates/components/ilios-calendar-event.hbs
  app/styles/ilios-common/components/ilios-calendar.scss
Labels: in progress

#240 link ci sequence blocks to excluded sessions.
  addon/models/curriculum-inventory-sequence-block.js
Labels: ready for review
