Repository ilios/common, pull requests merged in 2019-12, with the labels that each got.

#1010 Cache config from API server
  addon/services/ilios-config.js
Labels: ready for review

#1013 Add dependency linting
  package-lock.json
  package.json
Labels: ready for review

#1014 Only fetch configuration once
  addon/services/ilios-config.js
Labels: ready for review

#1017 Replace intersection-count helper
  addon/components/collapsed-taxonomies.hbs
Labels: ready for review

#1016 Use contains instead of is-in
  addon/components/course-header.hbs
  addon/components/course-objective-list-item.hbs
  addon/components/course-objective-list.hbs
  addon/components/course-overview.hbs
  addon/components/course-rollover.hbs
  addon/components/learningmaterial-manager.hbs
  addon/components/new-learningmaterial.hbs
  addon/components/new-objective.hbs
  addon/components/new-session.hbs
  addon/components/offering-form.hbs
  addon/components/publish-all-sessions.hbs
  addon/components/session-copy.hbs
  addon/components/session-objective-list-item.hbs
  addon/components/session-objective-list.hbs
  addon/components/session-overview.hbs
  addon/components/sessions-grid-offering.hbs
  tests/integration/helpers/is-in-test.js
Labels: ready for review

#1018 [breaking] completely replace and remove `is-in` helper
  addon/components/course-objective-list.hbs
  addon/components/dashboard-calendar.hbs
  addon/components/selected-term-tree.hbs
  addon/components/session-objective-list.hbs
  addon/helpers/is-in.js
  app/helpers/is-in.js
  tests/integration/helpers/is-in-test.js
  tests/unit/helpers/is-in-test.js
Labels: ready for review

#1020 [breaking] Remove not-in helpers
  addon/components/publish-all-sessions.hbs
  addon/helpers/not-in.js
  app/helpers/not-in.js
  tests/unit/helpers/not-in-test.js
Labels: ready for review

#1019 [breaking] Remove intersection-count helper
  addon/helpers/intersection-count.js
  app/helpers/intersection-count.js
  tests/integration/helpers/intersection-count-test.js
  tests/unit/helpers/intersection-count-test.js
Labels: ready for review

#1022 glimmerizes WaitSaving component.
  addon/components/wait-saving.hbs
  addon/components/wait-saving.js
Labels: ready for review

#1021 glimmerized WeekGlance component.
  addon/components/week-glance.hbs
  addon/components/week-glance.js
Labels: ready for review

#1029 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, ready for review

#1024 Convert <CourseMaterials> into a glimmer component
  addon-test-support/ilios-common/page-objects/components/course-materials.js
  addon/components/course-materials.hbs
  addon/components/course-materials.js
  tests/dummy/app/templates/course-materials.hbs
  tests/integration/components/course-materials-test.js
Labels: code quality, ready for review

#1008 Course Overview Glimmer Conversion
  addon-test-support/ilios-common/page-objects/components/course-overview.js
  addon-test-support/ilios-common/page-objects/course.js
  addon/components/course-overview.hbs
  addon/components/course-overview.js
  addon/decorators/validation.js
  addon/decorators/validation/after-date.js
  addon/decorators/validation/before-date.js
  addon/decorators/validation/length.js
  addon/decorators/validation/validatable.js
  package-lock.json
  package.json
  tests/acceptance/course/overview-test.js
  tests/integration/components/course-overview-test.js
Labels: code quality, ready for review

#1038 glimmerizes components
  addon-test-support/ilios-common/page-objects/components/offering-form.js
  addon-test-support/ilios-common/page-objects/session.js
  addon/components/time-picker.hbs
  addon/components/time-picker.js
  addon/components/timed-release-schedule.hbs
  addon/components/timed-release-schedule.js
  addon/components/toggle-buttons.hbs
  addon/components/toggle-buttons.js
  addon/components/toggle-icons.hbs
  addon/components/toggle-icons.js
  addon/components/toggle-yesno.hbs
  addon/components/toggle-yesno.js
  addon/components/user-search.hbs
  addon/components/user-search.js
  tests/integration/components/offering-form-test.js
  tests/integration/components/toggle-yesno-test.js
Labels: ready for review

#1050 Fix authentication type computed property
  addon/services/ilios-config.js
  tests/unit/services/ilios-config-test.js
Labels: ready for review

#1049 Fixes user search with promises
  addon/components/user-search.hbs
  addon/components/user-search.js
  tests/integration/components/user-search-test.js
Labels: ready for review

#1043 Octanify <CourseSessions> Component
  addon/components/course-sessions.hbs
  addon/components/course-sessions.js
  tests/acceptance/course/publishall-test.js
Labels: code quality, ready for review

#1046 December to Glimmer
  addon/components/course-publicationcheck.js
  addon/components/course-summary-header.hbs
  addon/components/course-summary-header.js
  addon/components/dashboard-agenda.hbs
  addon/components/dashboard-agenda.js
  addon/components/dashboard-materials.hbs
  addon/components/dashboard-materials.js
  addon/components/dashboard-view-picker.hbs
  addon/components/dashboard-view-picker.js
  addon/components/dashboard-week.hbs
  addon/components/dashboard-week.js
  addon/components/detail-cohort-list.hbs
  addon/components/detail-cohort-list.js
  addon/components/detail-cohort-manager.hbs
  addon/components/detail-cohort-manager.js
  tests/acceptance/course/publicationcheck-test.js
  tests/integration/components/course-summary-header-test.js
  tests/integration/components/dashboard-agenda-test.js
  tests/integration/components/detail-cohort-list-test.js
Labels: code quality, ready for review

#1039 Glimmer <CourseHeader>
  addon-test-support/ilios-common/page-objects/components/course-header.js
  addon-test-support/ilios-common/page-objects/components/course/publication-menu.js
  addon/components/course-header.hbs
  addon/components/course-header.js
  addon/components/course/publication-menu.hbs
  addon/components/course/publication-menu.js
  addon/decorators/validation.js
  addon/decorators/validation/length.js
  addon/decorators/validation/not-blank.js
  app/components/course/publication-menu.js
  app/styles/ilios-common/components/course-header.scss
  app/styles/ilios-common/components/publish-menu.scss
  tests/acceptance/course/publish-test.js
  tests/integration/components/course-header-test.js
  tests/integration/components/course/publication-menu-test.js
Labels: code quality, ready for review

#1053 Update Transitive Dependencies
  package-lock.json
Labels: ready for review

#1055 Cache current user model
  addon/services/current-user.js
  tests/integration/services/current-user-test.js
Labels: ready for review

#1051 Improve font loading
  app/styles/ilios-common/fonts.scss
  app/styles/ilios-common/fonts/nunito-sans.scss
  app/styles/ilios-common/fonts/nunito.scss
  app/styles/ilios-common/styles.scss
  config/environment.js
  index.js
  package-lock.json
  package.json
Labels: ready for review

#1057 glimmerizes TaxonomyManager and subcomponents
  addon/components/detail-taxonomies.hbs
  addon/components/selectable-terms-list-item.hbs
  addon/components/selectable-terms-list-item.js
  addon/components/selectable-terms-list.hbs
  addon/components/selectable-terms-list.js
  addon/components/taxonomy-manager.hbs
  addon/components/taxonomy-manager.js
  tests/integration/components/selectable-terms-list-item-test.js
  tests/integration/components/selectable-terms-list-test.js
  tests/integration/components/taxonomy-manager-test.js
Labels: ready for review

#1060 Fix file upload button display
  app/styles/ilios-common/components/learning-material-uploader.scss
Labels: ready for review

#1062 modernized/improved taxonomy manager test coverage
  tests/integration/components/selectable-terms-list-item-test.js
  tests/integration/components/selectable-terms-list-test.js
  tests/integration/components/taxonomy-manager-test.js
Labels: ready for review

#1058 supports backend v1.42
  config/api-version.js
Labels: ready for review

#1072 Stop removing focus outline from buttons
  app/styles/ilios-common/components/dashboard-view-picker.scss
  app/styles/ilios-common/components/single-event-objective-list.scss
Labels: ready for review

#1071 Add <title> of ilios to index.html
  index.js
  tests/dummy/app/index.html
Labels: ready for review

#1070 glimmerizes SingleEventLearningmaterialList component
  addon/components/single-event-learningmaterial-list.hbs
  addon/components/single-event-learningmaterial-list.js
  tests/integration/components/single-event-learningmaterial-list-test.js
Labels: ready for review

#1069 glimmerizes SingleEventObjectiveList component
  addon/components/single-event-objective-list.hbs
  addon/components/single-event-objective-list.js
  tests/integration/components/single-event-objective-list-test.js
Labels: ready for review

#1065 glimmerizes SortableTh and SortableHeader component.
  addon/components/sortable-heading.hbs
  addon/components/sortable-heading.js
  addon/components/sortable-th.hbs
  addon/components/sortable-th.js
  tests/integration/components/sortable-heading-test.js
  tests/integration/components/sortable-th-test.js
Labels: ready for review

#1066 The Marvelous Mrs Glimmer
  addon/components/detail-cohorts.hbs
  addon/components/detail-cohorts.js
  addon/components/detail-competencies.hbs
  addon/components/detail-competencies.js
  addon/components/detail-instructors-list.hbs
  addon/components/detail-instructors-list.js
  addon/components/detail-instructors.hbs
  addon/components/detail-instructors.js
Labels: code quality, ready for review

#1074 Update to Ember 3.15
  .ember-cli
  .npmignore
  .travis.yml
  README.md
  config/ember-try.js
  package-lock.json
  package.json
  tests/dummy/app/app.js
  tests/dummy/app/resolver.js
  tests/dummy/app/templates/components/.gitkeep
  tests/dummy/config/optional-features.json
Labels: dependencies, ready for review

#1073 Clean up label on download links
  addon/components/week-glance-event.hbs
  tests/integration/components/week-glance-event-test.js
Labels: ready for review

#1067 Glimmerizes MyMaterials component
  addon/components/my-materials.hbs
  addon/components/my-materials.js
  addon/mixins/sortable-table.js
  addon/templates/mymaterials.hbs
  tests/integration/components/my-materials-test.js
  tests/unit/mixins/sortable-table-test.js
Labels: ready for review
