Repository ilios/common, pull requests merged in 2019-01, with the labels that each got.

#417 Update Ember cli 3.6 blueprints
  .npmignore
  .travis.yml
  CONTRIBUTING.md
  LICENSE.md
  README.md
  config/ember-try.js
  package.json
  tests/dummy/config/deprecation-workflow.js
  yarn.lock
Labels: in progress

#422 bumped up math helpers dependency.
  package.json
  yarn.lock
Labels: in progress, ready for review

#428 Drop support for old node versions
  .nvmrc
  .travis.yml
  package.json
Labels: in progress, ready for review

#426 Session linking in the Admin UI
  addon/components/session-overview.js
  addon/mixins/session-route.js
  addon/models/session.js
  addon/templates/components/session-overview.hbs
  app/styles/ilios-common/components/session-overview.scss
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: in progress

#432 Test coverage session linking admin ui
  addon-test-support/ilios-common/page-objects/session.js
  tests/acceptance/course/session/ilm-test.js
  tests/acceptance/course/session/overview-test.js
Labels: in progress, ready for review

#437 Remove greenkeeper
  .travis.yml
  README.md
  package.json
Labels: in progress, ready for review

#434 consider changes to administered courses when calculating "my courses"
  addon/services/current-user.js
Labels: ready for review

#446 guard against method invocation with empty element as input
  addon/components/html-editor.js
Labels: in progress

#452 Feature flag session linking admin component
  addon/components/session-overview.js
  addon/templates/components/session-overview.hbs
  config/environment.js
  package.json
  tests/acceptance/course/session/overview-test.js
  yarn.lock
Labels: in progress, ready for review

#436 Improved Linting
  .stylelintrc
  .travis.yml
  app/styles/ilios-common/components/ilios-calendar.scss
  app/styles/ilios-common/components/single-event-objective-list.scss
  package.json
  yarn.lock
Labels: in progress, ready for review

#411 Display Prerequisite Events
  addon-mirage-support/factories/schoolevent.js
  addon-mirage-support/factories/userevent.js
  addon-test-support/ilios-common/page-objects/components/dashboard-week.js
  addon-test-support/ilios-common/page-objects/components/ilios-calendar-pre-work-event.js
  addon-test-support/ilios-common/page-objects/components/single-event.js
  addon-test-support/ilios-common/page-objects/components/week-glance-event.js
  addon-test-support/ilios-common/page-objects/components/week-glance-pre-work.js
  addon-test-support/ilios-common/page-objects/components/week-glance.js
  addon/components/dashboard-week.js
  addon/components/ilios-calendar-day.js
  addon/components/ilios-calendar-month.js
  addon/components/ilios-calendar-pre-work-event.js
  addon/components/ilios-calendar-pre-work-events.js
  addon/components/ilios-calendar-week.js
  addon/components/lm-type-icon.js
  addon/components/single-event.js
  addon/components/week-glance-event.js
  addon/components/week-glance-pre-work.js
  addon/components/week-glance.js
  addon/mixins/events.js
  addon/services/school-events.js
  addon/services/user-events.js
  addon/templates/components/dashboard-week.hbs
  addon/templates/components/ilios-calendar-day.hbs
  addon/templates/components/ilios-calendar-month.hbs
  addon/templates/components/ilios-calendar-pre-work-event.hbs
  addon/templates/components/ilios-calendar-pre-work-events.hbs
  addon/templates/components/ilios-calendar-week.hbs
  addon/templates/components/single-event.hbs
  addon/templates/components/week-glance-event.hbs
  addon/templates/components/week-glance-pre-work.hbs
  addon/templates/components/week-glance.hbs
  app/components/ilios-calendar-pre-work-event.js
  app/components/ilios-calendar-pre-work-events.js
  app/components/week-glance-event.js
  app/components/week-glance-pre-work.js
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/ilios-calendar-pre-work-events.scss
  app/styles/ilios-common/components/week-glance-pre-work.scss
  app/styles/ilios-common/components/week-glance.scss
  tests/integration/components/dashboard-week-test.js
  tests/integration/components/ilios-calendar-month-test.js
  tests/integration/components/ilios-calendar-pre-work-event-test.js
  tests/integration/components/ilios-calendar-pre-work-events-test.js
  tests/integration/components/single-event-test.js
  tests/integration/components/week-glance-event-test.js
  tests/integration/components/week-glance-pre-work-test.js
  tests/integration/components/week-glance-test.js
  tests/integration/services/school-events-test.js
  tests/integration/services/user-events-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: in progress, ready for review

#457 Filter events correctly
  addon/components/ilios-calendar-day.js
  addon/components/ilios-calendar-month.js
  addon/components/ilios-calendar-week.js
  addon/components/week-glance.js
Labels: in progress, ready for review

#469 Update Dependencies
  yarn.lock
Labels: in progress

#471 Add pre and post requisite dummy data to offering calendar events
  addon/components/offering-calendar.js
  tests/integration/components/offering-calendar-test.js
Labels: in progress, ready for review
