Repository ilios/common, pull requests merged in 2019-02, with the labels that each got.

#485 move slug generation functionality into mixin.
  addon/mixins/events.js
  addon/services/school-events.js
  addon/services/user-events.js
  tests/integration/services/school-events-test.js
  tests/integration/services/user-events-test.js
  tests/unit/mixins/events-test.js
Labels: in progress, ready for review

#487 config for rendering pre-work as clickable links or plain text
  addon-test-support/ilios-common/page-objects/components/ilios-calendar-pre-work-event.js
  addon/components/ilios-calendar-day.js
  addon/components/ilios-calendar-month.js
  addon/templates/components/ilios-calendar-day.hbs
  addon/templates/components/ilios-calendar-month.hbs
  addon/templates/components/ilios-calendar-pre-work-event.hbs
  addon/templates/components/ilios-calendar-pre-work-events.hbs
  addon/templates/components/ilios-calendar-week.hbs
  addon/templates/components/single-event.hbs
  addon/templates/components/week-glance-pre-work.hbs
  tests/integration/components/ilios-calendar-pre-work-event-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: ready for review

#491 fix cleanQuery() bug
  addon/utils/query-utils.js
  tests/integration/components/leadership-search-test.js
Labels: in progress, ready for review

#493 Remove Unused Dashbaord Page Object
  addon-test-support/ilios-common/page-objects/dashboard.js
Labels: in progress

#494 Skip course LMs in Week at a Glance
  addon/templates/components/week-glance-event.hbs
  tests/integration/components/week-glance-event-test.js
Labels: in progress

#495 Switch from ordinals to bullets
  addon/templates/components/single-event.hbs
Labels: in progress

#501 render lang string with embedded markup.
  addon/templates/components/offering-calendar.hbs
Labels: ready for review

#500 Enable session linking
  config/environment.js
Labels: in progress, ready for review

#498 kebap-casing pre-work.
  translations/en-us.yaml
Labels: ready for review

#496 Add first offering date to postrequisite dropdown
  addon/mixins/session/index-route.js
  addon/templates/components/session-overview.hbs
  tests/acceptance/course/session/overview-test.js
Labels: in progress, ready for review

#511 Upgrade our version of ember-simple-charts
  package.json
  yarn.lock
Labels: in progress

#512 re-implements instructor-group search in user-search component
  addon/components/user-search.js
Labels: ready for review

#513 Automatically Publish Tags to NPM
  .travis.yml
Labels: in progress, ready for review

#518 Reorganize the way the JWT is found
  addon/services/ajax.js
Labels: in progress, ready for review

#514 Remove overridden promise
  addon/initializers/replace-promise.js
  app/initializers/replace-promise.js
  tests/dummy/config/targets.js
  tests/unit/initializers/replace-promise-test.js
Labels: in progress, ready for review

#516 Improve calendar loading
  addon/components/ilios-calendar-day.js
  addon/components/ilios-calendar-week.js
Labels: ready for review

#529 Use shared ilios addon eslint config
  .eslintrc.js
  addon/components/weekly-events.js
  addon/helpers/is-in.js
  addon/models/academic-year.js
  addon/models/course.js
  addon/models/school.js
  package.json
  yarn.lock
Labels: in progress

#527 Declare the icons we need
  config/icons.js
  package.json
  tests/dummy/config/environment.js
  tests/integration/components/offering-calendar-test.js
  yarn.lock
Labels: in progress, ready for review

#533 Use the latest ilios eslint config
  .eslintrc.js
  package.json
  yarn.lock
Labels: in progress, ready for review

#536 Add a null check when escaping regex
  addon/utils/escape-reg-exp.js
  tests/unit/utils/escape-reg-exp-test.js
Labels: in progress, ready for review

#528 Dedupe pre post requisites
  addon-test-support/ilios-common/page-objects/components/week-glance-pre-work.js
  addon/components/week-glance-pre-work.js
  addon/components/week-glance.js
  addon/templates/components/week-glance-pre-work.hbs
  addon/templates/components/week-glance.hbs
  tests/integration/components/week-glance-pre-work-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: ready for review

#538 Replace yarn with NPM
  .travis.yml
  package-lock.json
  yarn.lock
Labels: in progress

#537 Apply linting to routes
  .eslintrc.js
  addon/templates/components/course-header.hbs
  addon/templates/components/course-overview.hbs
  addon/templates/components/course-summary-header.hbs
  addon/templates/components/session-overview.hbs
  tests/acceptance/course/publicationcheck-test.js
  tests/acceptance/course/session/publicationcheck-test.js
  tests/dummy/app/router.js
  tests/integration/components/publish-menu-test.js
Labels: in progress, ready for review

#540 Icon consistency
  addon/templates/components/course-objective-list-item.hbs
  addon/templates/components/detail-learning-materials.hbs
  addon/templates/components/editable-field.hbs
  addon/templates/components/offering-manager.hbs
  addon/templates/components/session-objective-list-item.hbs
  addon/templates/components/sessions-grid.hbs
  app/styles/ilios-common/components/detail-learningmaterials.scss
  app/styles/ilios-common/components/editinplace.scss
  app/styles/ilios-common/components/learningmaterial-manager.scss
  app/styles/ilios-common/components/objective-list-item.scss
  app/styles/ilios-common/components/offering-manager.scss
  app/styles/ilios-common/components/session-overview.scss
  app/styles/ilios-common/components/sessions-grid.scss
  app/styles/ilios-common/mixins.scss
  app/styles/ilios-common/mixins/icon.scss
Labels: ready for review

#542 Move ember-data into dependencies
  package-lock.json
  package.json
Labels: in progress, ready for review

#541 Copy notes with the session
  addon/components/session-copy.js
  tests/integration/components/session-copy-test.js
Labels: in progress, ready for review

#544 Update to Ember CLI 3.8
  .gitignore
  README.md
  package-lock.json
  package.json
Labels: in progress, ready for review
