Repository ilios/common, pull requests merged in 2019-04, with the labels that each got.

#602 updated session table first offering column display control flow
  addon/components/course-sessions.js
  addon/templates/components/sessions-grid.hbs
  app/styles/ilios-common/mixins/sessions-grid.scss
  config/icons.js
Labels: ready, ready for review

#599 fixed buggy time inputs
  addon/components/offering-form.js
  addon/templates/components/offering-form.hbs
  app/styles/ilios-common/components/offering-form.scss
Labels: in progress, ready for review

#609 corrected variable name.
  translations/fr.yaml
Labels: in progress, ready for review

#596 course learning materials sort and search additions
  addon/components/course-materials.js
  addon/mixins/course-materials-controller.js
  addon/mixins/sortable-table.js
  addon/templates/components/course-materials.hbs
  app/styles/ilios-common/components/course-materials.scss
  tests/integration/components/course-materials-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: in progress, ready for review

#608 collapsed-objective-program-years component
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: in progress, ready for review

#613 updates lock file with correct common version.
  package-lock.json
Labels: ready, ready for review

#615 Use template linter from ilios
  .template-lintrc.js
  addon/templates/components/boolean-check.hbs
  addon/templates/components/course-editing.hbs
  addon/templates/components/learningmaterial-manager.hbs
  package-lock.json
  package.json
  tests/dummy/app/templates/course-materials.hbs
  tests/dummy/app/templates/course-visualizations.hbs
  tests/dummy/app/templates/course-visualize-objectives.hbs
Labels: in progress, ready for review

#614 Update to ember v3.9
  package-lock.json
  package.json
  tests/dummy/config/deprecation-workflow.js
  tests/dummy/config/environment.js
Labels: in progress, ready for review

#627 Update Dependencies
  .eslintrc.js
  package-lock.json
Labels: in progress

#623 preserve session-list scroll
  addon/components/sessions-grid.js
  addon/mixins/course/index-route.js
  addon/services/preserve-scroll.js
  app/services/preserve-scroll.js
  package-lock.json
  package.json
Labels: ready, ready for review

#636 rm double-indent, correct color overrides.
  addon/templates/components/leadership-search.hbs
  app/styles/ilios-common/mixins/user-search.scss
  tests/integration/components/leadership-search-test.js
Labels: ready for review

#641 smoother comprehensive transition when adding new MeSH terms
  addon/components/detail-objectives.js
  addon/templates/components/detail-objectives.hbs
  addon/templates/components/objective-manage-descriptors.hbs
  app/styles/ilios-common/components/detail-objectives.scss
Labels: ready for review

#642 offerings UI style fixes
  addon/templates/components/learnergroup-selection-manager.hbs
  app/styles/ilios-common/components/learnergroup-selection-manager.scss
  app/styles/ilios-common/components/offering-form.scss
Labels: ready for review

#643 better course objective removal warning message
  addon/templates/components/course-objective-list.hbs
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: ready for review

#629 added query params for all 5 additional checkbox-filters
  addon/components/common-dashboard.js
  addon/components/dashboard-calendar.js
  addon/mixins/dashboard-controller.js
  addon/templates/components/common-dashboard.hbs
  addon/templates/components/dashboard-calendar.hbs
  tests/acceptance/dashboard/calendar-test.js
  tests/dummy/app/templates/dashboard.hbs
Labels: in progress

#651 corrects french translation of learning material(s)
  translations/fr.yaml
Labels: ready for review
