Repository ilios/common, pull requests merged in 2019-10, with the labels that each got.

#891 Silence more deprecations
  tests/dummy/config/deprecation-workflow.js
Labels: ready for review

#893 Add open source heroes list
  README.md
Labels: ready for review

#890 Remove some jquery
  addon/components/editable-field.js
  addon/components/search-box.js
  addon/components/session-details.js
  addon/utils/scroll-to.js
  tests/integration/components/editable-field-test.js
  tests/integration/components/search-box-test.js
Labels: ready for review

#902 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, ready for review

#908 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#904 display instructor group members.
  addon-test-support/ilios-common/page-objects/components/instructor-selection-manager.js
  addon-test-support/ilios-common/page-objects/session.js
  addon/components/detail-instructors.js
  addon/templates/components/detail-instructors-list.hbs
  addon/templates/components/detail-instructors.hbs
  addon/templates/components/instructor-selection-manager.hbs
  app/styles/ilios-common/components/detail-instructors-list.scss
  app/styles/ilios-common/components/instructor-selection-manager.scss
  tests/acceptance/course/session/ilm-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: ready for review

#898 Remove more jquery
  addon/helpers/remove-html-tags.js
  addon/models/school.js
  addon/utils/query-utils.js
  tests/unit/models/school-test.js
Labels: ready for review

#918 Get course from the event
  addon/mixins/events.js
  tests/acceptance/dashboard/calendar-test.js
  tests/unit/mixins/events-test.js
Labels: ready for review

#922 Add missing university icon
  config/icons.js
Labels: ready for review

#924 Lint for and remove final implicit this usages
  .template-lintrc.js
  addon/templates/components/course-editing.hbs
  addon/templates/components/course-objective-list.hbs
  addon/templates/components/detail-cohorts.hbs
  addon/templates/components/ilios-calendar-day.hbs
  addon/templates/components/learnergroup-tree.hbs
  addon/templates/components/loading-part.hbs
  addon/templates/components/offering-form.hbs
  addon/templates/components/selected-term-tree.hbs
  addon/templates/components/session-overview.hbs
  addon/templates/components/single-event-objective-list.hbs
  addon/templates/events.hbs
  addon/templates/weeklyevents.hbs
  tests/dummy/app/templates/course.hbs
  tests/dummy/app/templates/course/index.hbs
  tests/dummy/app/templates/course/publication-check.hbs
  tests/dummy/app/templates/course/publishall.hbs
  tests/dummy/app/templates/course/rollover.hbs
  tests/dummy/app/templates/dashboard.hbs
  tests/dummy/app/templates/login.hbs
  tests/dummy/app/templates/print-course.hbs
  tests/dummy/app/templates/session/copy.hbs
  tests/dummy/app/templates/session/index.hbs
  tests/dummy/app/templates/session/publication-check.hbs
Labels: ready for review

#931 Update to Ember CLI 3.13
  .npmignore
  .travis.yml
  addon/components/session-overview.js
  addon/models/session.js
  addon/templates/components/session-overview.hbs
  package-lock.json
  package.json
  tests/unit/models/learner-group-test.js
Labels: ready for review

#925 Remove jQuery from auth flow
  addon/authenticators/ilios-jwt.js
  tests/dummy/config/environment.js
Labels: ready for review

#926 Use fetch API in place of ember-ajax
  addon/components/course-rollover.js
  addon/components/dashboard-materials.js
  addon/components/offering-calendar.js
  addon/routes/mymaterials.js
  addon/services/fetch.js
  addon/services/ilios-config.js
  addon/services/school-events.js
  addon/services/user-events.js
  app/services/fetch.js
  package-lock.json
  package.json
  tests/integration/components/course-rollover-test.js
  tests/integration/components/dashboard-materials-test.js
  tests/integration/services/school-events-test.js
  tests/integration/services/user-events-test.js
  tests/unit/services/fetch-test.js
Labels: ready for review

#940 Improve sorting icons
  addon/components/sortable-heading.js
  addon/components/sortable-th.js
  config/icons.js
Labels: ready for review
