Repository ilios/common, pull requests merged in 2020-01, with the labels that each got.

#1091 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, ready for review

#1076 glimmerizes SingleEvent component.
  addon/components/single-event.hbs
  addon/components/single-event.js
  tests/integration/components/single-event-test.js
Labels: ready for review

#1094 Octanify <DetailLearningMaterials> component
  addon-test-support/ilios-common/page-objects/components/learning-materials.js
  addon/components/detail-learning-materials.hbs
  addon/components/detail-learning-materials.js
  addon/components/learning-materials-sort-manager.hbs
  addon/components/learning-materials-sort-manager.js
  addon/utils/sortable-by-position.js
  app/utils/sortable-by-position.js
  tests/integration/components/detail-learning-materials-test.js
  tests/integration/components/learning-materials-sort-manager-test.js
  tests/unit/utils/sortable-by-position-test.js
Labels: code quality, ready for review

#1080 glimmerizes SessionsGrid components
  addon/components/sessions-grid-header.hbs
  addon/components/sessions-grid-header.js
  addon/components/sessions-grid-last-updated.hbs
  addon/components/sessions-grid-last-updated.js
  addon/components/sessions-grid-loading.hbs
  addon/components/sessions-grid-loading.js
  addon/components/sessions-grid-offering-table.hbs
  addon/components/sessions-grid-offering-table.js
  addon/components/sessions-grid-offering.hbs
  addon/components/sessions-grid-offering.js
  addon/components/sessions-grid.hbs
  addon/components/sessions-grid.js
  addon/utils/offering-date-block.js
  package-lock.json
  package.json
Labels: ready for review

#1101 Ensure school is set before accessing it
  addon/components/dashboard-calendar.js
Labels: ready for review

#1099 Fix a11y issue with download icons
  addon/components/single-event-learningmaterial-list.hbs
  addon/components/single-event-learningmaterial-list.js
  tests/integration/components/single-event-learningmaterial-list-test.js
  tests/integration/components/single-event-test.js
Labels: ready for review

#1105 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#1108 Add ember-ref-modifier as dependency
  package.json
Labels: dependencies

#1098 glimmerizes <SessionPublicationcheck> component
  addon/components/session-publicationcheck.hbs
  addon/components/session-publicationcheck.js
  tests/integration/components/session-publicationcheck-test.js
Labels: ready for review

#1107 Fix header levels
  addon/components/single-event.hbs
  addon/components/week-glance.hbs
  app/styles/ilios-common/components/single-event.scss
  app/styles/ilios-common/components/week-glance.scss
  tests/integration/components/week-glance-test.js
Labels: ready for review

#1106 Add labels to expand / collapse buttons
  addon/components/expand-collapse-button.hbs
Labels: ready for review

#1118 Align header levels
  addon/components/week-glance-event.hbs
  addon/components/week-glance.hbs
  app/styles/ilios-common/components/week-glance.scss
Labels: ready for review

#1124 Temporarily disable tests
  .travis.yml
Labels: ready for review

#1122 Remove nullish coalescing plugin
  index.js
  package-lock.json
  package.json
Labels: dependencies, ready for review

#1127 [breaking] Use provided click outside modifier
  addon/components/choose-material-type.hbs
  addon/components/course/publication-menu.hbs
  addon/modifiers/handle-click-outside.js
  app/modifiers/handle-click-outside.js
  tests/integration/modifiers/handle-click-outside-test.js
Labels: ready for review

#1111 The Octane Timeline (it's the best one!)
  addon/components/detail-taxonomies.hbs
  addon/components/detail-taxonomies.js
  addon/components/detail-terms-list-item.hbs
  addon/components/detail-terms-list-item.js
  addon/components/detail-terms-list.hbs
  addon/components/detail-terms-list.js
  addon/components/expand-collapse-button.hbs
  addon/components/expand-collapse-button.js
  addon/components/ics-feed.hbs
  addon/components/ics-feed.js
  tests/integration/components/detail-terms-list-item-test.js
  tests/integration/components/detail-terms-list-test.js
Labels: code quality, ready for review

#1110 Octaneify MeSH
  addon-mirage-support/get-all.js
  addon-test-support/ilios-common/page-objects/components/mesh-manager.js
  addon/components/detail-mesh.hbs
  addon/components/detail-mesh.js
  addon/components/mesh-manager.hbs
  addon/components/mesh-manager.js
  tests/integration/components/mesh-manager-test.js
Labels: code quality, ready for review

#1130 Add netlify build badge
  README.md
Labels: ready for review

#1135 Temporarily disable ember-release tests
  .travis.yml
Labels: ready for review

#1137 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#1136 glimmerize SessionOverview component.
  addon-test-support/ilios-common/page-objects/components/session/publication-menu.js
  addon/components/session-overview.hbs
  addon/components/session-overview.js
  addon/components/session-publicationcheck.hbs
  addon/components/session/publication-menu.hbs
  addon/components/session/publication-menu.js
  addon/decorators/validation.js
  addon/decorators/validation/gte.js
  app/components/session/publication-menu.js
  app/styles/ilios-common/components/session-overview.scss
  tests/integration/components/session-publicationcheck-test.js
  tests/integration/components/session/publication-menu-test.js
Labels: ready for review

#1144 Silence is-visible deprecation
  tests/dummy/config/deprecation-workflow.js
Labels: ready for review

#1145 Fix detail filter on calendar
  addon/components/dashboard-calendar.js
  tests/acceptance/dashboard/calendar-test.js
Labels: ready for review

#1131 Replace TravisCI with Github Actions
  .github/workflows/ci.yaml
  .github/workflows/future-ci.yaml
  .github/workflows/release.yaml
  .travis.yml
Labels: ready for review

#1148 glimmerizes OfferingCalendar component.
  addon/components/offering-calendar.hbs
  addon/components/offering-calendar.js
Labels: ready for review
