Repository ilios/common, pull requests merged in 2020-03, with the labels that each got.

#1202 always show timed release info if end date is given.
  addon/components/timed-release-schedule.hbs
  addon/components/timed-release-schedule.js
  tests/integration/components/timed-release-schedule-test.js
Labels: ready for review

#1209 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#1206 adds title to eye-icon.
  addon-test-support/ilios-common/page-objects/components/learning-materials.js
  addon/components/detail-learning-materials.hbs
  tests/integration/components/detail-learning-materials-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: ready for review

#1218 prevent course leadership manager interaction until all data has loaded.
  addon/components/course-leadership-expanded.hbs
  addon/components/course-leadership-expanded.js
Labels: ready for review

#1207 [breaking] My Oh My Octane!
  addon/components/course-overview.js
  addon/components/detail-learning-materials.hbs
  addon/components/leadership-search.hbs
  addon/components/leadership-search.js
  addon/components/learningmaterial-manager.hbs
  addon/components/learningmaterial-manager.js
  addon/components/learningmaterial-search.hbs
  addon/components/learningmaterial-search.js
  addon/components/lm-type-icon.hbs
  addon/components/lm-type-icon.js
  addon/components/loading-part.js
  addon/components/loading-spinner.hbs
  addon/components/loading-spinner.js
  addon/decorators/validation/after-date.js
  addon/decorators/validation/before-date.js
  package-lock.json
  package.json
  tests/integration/components/leadership-search-test.js
  tests/integration/components/lm-type-icon-test.js
Labels: ready for review

#1220 fixes scroll into view upon offering form closing.
  addon/components/sessions-grid-offering.hbs
  addon/components/sessions-grid-offering.js
Labels: bug, ready for review

#1222 corrects passing of title attribute to the icon.
  addon-test-support/ilios-common/page-objects/components/session/postrequisite-editor.js
  addon/components/session/postrequisite-editor.hbs
  tests/integration/components/session/postrequisite-editor-test.js
Labels: ready for review

#1225 remove PublishMenu component
  addon/components/course/publication-menu.hbs
  addon/components/publish-menu.hbs
  addon/components/publish-menu.js
  addon/components/session/publication-menu.hbs
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/publication-menu.scss
  tests/acceptance/course/publish-test.js
  tests/acceptance/course/session/publish-test.js
  tests/integration/components/publish-menu-test.js
Labels: ready for review

#1231 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#1235 prevent selected terms from being added.
  addon/components/mesh-manager.js
  tests/integration/components/mesh-manager-test.js
Labels: ready for review

#1243 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#1242 [breaking] Here's looking at you Octane
  addon/components/course-header.hbs
  addon/components/course-summary-header.hbs
  addon/components/new-learningmaterial.hbs
  addon/components/new-learningmaterial.js
  addon/components/new-objective.hbs
  addon/components/new-objective.js
  addon/components/new-offering.hbs
  addon/components/new-offering.js
  addon/components/new-session.hbs
  addon/components/new-session.js
  addon/components/not-found.hbs
  addon/components/not-found.js
  addon/components/offering-manager.hbs
  addon/components/offering-manager.js
  addon/components/print-course.hbs
  addon/components/print-course.js
  addon/components/progress-bar.hbs
  addon/components/progress-bar.js
  addon/components/publication-status.hbs
  addon/components/publication-status.js
  addon/components/session-overview.hbs
  addon/components/sessions-grid.hbs
  addon/decorators/validation/validatable.js
  tests/acceptance/course/learningmaterials-test.js
  tests/acceptance/course/session/learningmaterials-test.js
  tests/integration/components/publication-status-test.js
Labels: ready for review

#1246 [breaking] Remove unused objective components
  addon/components/detail-objectives.hbs
  addon/components/detail-objectives.js
  addon/components/objective-manage-competency.hbs
  addon/components/objective-manage-competency.js
  addon/components/objective-manage-descriptors.hbs
  addon/components/objective-manage-descriptors.js
  app/components/detail-objectives.js
  app/components/objective-manage-competency.js
  app/components/objective-manage-descriptors.js
Labels: ready for review

#1247 Flash of Octane
  addon/components/pulse-loader.hbs
  addon/components/pulse-loader.js
  addon/components/selected-term-tree.hbs
  addon/components/selected-term-tree.js
Labels: ready for review

#1245 scroll bottom of offering form into view when it gets opened up.
  addon/components/new-offering.hbs
  addon/components/offering-form.hbs
  addon/components/offering-form.js
  addon/components/offering-manager.hbs
  addon/components/sessions-grid-offering.hbs
Labels: ready for review

#1252 Octane objective lists
  addon-test-support/ilios-common/page-objects/components/course/objective-list-item.js
  addon-test-support/ilios-common/page-objects/components/course/objective-list.js
  addon-test-support/ilios-common/page-objects/components/course/objectives.js
  addon-test-support/ilios-common/page-objects/components/session/objective-list-item.js
  addon-test-support/ilios-common/page-objects/components/session/objective-list.js
  addon-test-support/ilios-common/page-objects/components/session/objectives.js
  addon/components/course/objective-list-item.hbs
  addon/components/course/objective-list-item.js
  addon/components/course/objective-list.hbs
  addon/components/course/objective-list.js
  addon/components/course/objectives.hbs
  addon/components/session-objective-list-item.hbs
  addon/components/session-objective-list-item.js
  addon/components/session-objective-list.hbs
  addon/components/session-objective-list.js
  addon/components/session/objective-list-item.hbs
  addon/components/session/objective-list-item.js
  addon/components/session/objective-list.hbs
  addon/components/session/objective-list.js
  addon/components/session/objectives.hbs
  app/components/course-objective-list-item.js
  app/components/course-objective-list.js
  app/components/course/objective-list-item.js
  app/components/course/objective-list.js
  app/components/session-objective-list-item.js
  app/components/session-objective-list.js
  app/components/session/objective-list-item.js
  app/components/session/objective-list.js
  tests/acceptance/course/cohorts-test.js
  tests/acceptance/course/competencies-test.js
  tests/acceptance/course/objectivecreate-test.js
  tests/acceptance/course/objectivelist-test.js
  tests/acceptance/course/objectivemesh-test.js
  tests/acceptance/course/objectiveparents-multiplecohorts-test.js
  tests/acceptance/course/objectiveparents-nocohorts-test.js
  tests/acceptance/course/objectiveparents-test.js
  tests/acceptance/course/session/objectivecreate-test.js
  tests/acceptance/course/session/objectivelist-test.js
  tests/acceptance/course/session/objectivemesh-test.js
  tests/acceptance/course/session/objectiveparents-test.js
  tests/integration/components/course-objective-list-item-test.js
  tests/integration/components/course-objective-list-test.js
  tests/integration/components/course/objective-list-item-test.js
  tests/integration/components/course/objective-list-test.js
  tests/integration/components/course/objectives-test.js
  tests/integration/components/session-objective-list-item-test.js
  tests/integration/components/session-objective-list-test.js
  tests/integration/components/session/objective-list-item-test.js
  tests/integration/components/session/objective-list-test.js
  tests/integration/components/session/objectives-test.js
Labels: ready for review

#1254 Update Ember v3.16.0...v3.17.0
  .eslintrc.js
  .github/workflows/ci.yaml
  .github/workflows/future-ci.yaml
  .template-lintrc.js
  CONTRIBUTING.md
  addon/components/daily-calendar-event.hbs
  addon/components/ilios-calendar-event-month.hbs
  addon/components/weekly-calendar-event.hbs
  package-lock.json
  package.json
  testem.js
  tests/dummy/config/ember-cli-update.json
Labels: dependencies

#1262 link learners to offerings.
  addon-test-support/ilios-common/page-objects/components/detail-learner-list.js
  addon-test-support/ilios-common/page-objects/components/learner-selection-manager.js
  addon/components/detail-learner-list.hbs
  addon/components/learner-selection-manager.hbs
  addon/components/new-offering.js
  addon/components/offering-form.hbs
  addon/components/offering-form.js
  addon/components/offering-manager.js
  addon/components/sessions-grid-offering.js
  app/components/detail-learner-list.js
  app/components/learner-selection-manager.js
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/detail-learner-list.scss
  app/styles/ilios-common/components/offering-form.scss
  tests/integration/components/detail-learner-list-test.js
  tests/integration/components/learner-selection-manager-test.js
  tests/integration/components/offering-form-test.js
  translations/en-us.yaml
  translations/es.yaml
  translations/fr.yaml
Labels: ready for review

#1279 Update Transitive Dependencies
  package-lock.json
Labels: dependencies

#1278 rm unused toggle-icons component.
  addon/components/toggle-icons.hbs
  addon/components/toggle-icons.js
  app/components/toggle-icons.js
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/toggle-icons.scss
  tests/integration/components/toggle-icons-test.js
Labels: ready for review

#1283 rm unnecessary fn helper.
  addon/components/course-leadership-expanded.hbs
  addon/components/course-overview.hbs
  addon/components/detail-learning-materials.hbs
  addon/components/detail-mesh.hbs
  addon/components/offering-form.hbs
  addon/components/publish-all-sessions.hbs
  addon/components/session-leadership-expanded.hbs
  addon/components/session-offerings-list.hbs
  addon/components/session-overview.hbs
  addon/components/session-publicationcheck.hbs
  addon/components/sessions-grid-offering.hbs
  addon/components/single-event.hbs
  addon/components/visualizer-course-instructors.hbs
  addon/components/visualizer-course-session-types.hbs
  addon/components/visualizer-course-vocabularies.hbs
  addon/components/visualizer-course-vocabulary.hbs
  addon/templates/weeklyevents.hbs
  tests/dummy/app/templates/course/publishall.hbs
  tests/dummy/app/templates/course/rollover.hbs
  tests/dummy/app/templates/dashboard.hbs
  tests/dummy/app/templates/session/copy.hbs
  tests/integration/components/course/objective-list-item-test.js
  tests/integration/components/daily-calendar-test.js
  tests/integration/components/dashboard/filter-checkbox-test.js
  tests/integration/components/dashboard/selected-term-tree-test.js
  tests/integration/components/leadership-search-test.js
  tests/integration/components/learning-materials-sort-manager-test.js
  tests/integration/components/monthly-calendar-test.js
  tests/integration/components/objective-sort-manager-test.js
  tests/integration/components/session/objective-list-item-test.js
  tests/integration/components/weekly-calendar-test.js
Labels: ready for review

#1284 modernizes offering form integration test
  addon-test-support/ilios-common/page-objects/components/offering-form.js
  addon/components/offering-form.hbs
  tests/acceptance/course/session/offerings-management-test.js
  tests/acceptance/course/session/offerings-test.js
  tests/acceptance/course/sessionlist-test.js
  tests/integration/components/offering-form-test.js
Labels: ready for review

#1286 Make new objectives active by default
  addon/models/objective.js
  tests/unit/models/objective-test.js
Labels: ready for review
