Repository ilios/common, pull requests merged in 2020-02, with the labels that each got.

#1151 Glimmerizes LearnergroupTree component.
  addon/components/learnergroup-tree.hbs
  addon/components/learnergroup-tree.js
  tests/integration/components/learnergroup-tree-test.js
Labels: ready for review

#1152 Monthly Calendar as a CSS Grid
  addon-test-support/ilios-common/page-objects/components/monthly-calendar.js
  addon/components/ilios-calendar-event-month.js
  addon/components/ilios-calendar-month.hbs
  addon/components/monthly-calendar.hbs
  addon/components/monthly-calendar.js
  app/components/monthly-calendar.js
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/ilios-calendar.scss
  app/styles/ilios-common/components/monthly-calendar.scss
  tests/acceptance/dashboard/calendar-test.js
  tests/integration/components/ilios-calendar-month-test.js
  tests/integration/components/monthly-calendar-test.js
Labels: ready for review

#1142 Keep track of ILM status in component
  addon-test-support/ilios-common/page-objects/components/offering-form.js
  addon-test-support/ilios-common/page-objects/session.js
  addon/components/offering-form.hbs
  addon/components/session-overview.hbs
  addon/components/session-overview.js
  addon/components/toggle-yesno.hbs
  tests/integration/components/offering-form-test.js
Labels: ready for review

#1153 octanifies LearnergroupSelectionManager component.
  addon/components/learnergroup-selection-manager.hbs
  addon/components/learnergroup-selection-manager.js
Labels: ready for review

#1154 glimmerizes InstructorSelectionManager component.
  addon/components/instructor-selection-manager.hbs
  addon/components/instructor-selection-manager.js
Labels: ready for review

#1156 replace RSVP promise with async/await
  addon/components/offering-form.js
Labels: ready for review

#1157 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, ready for review

#1160 Change the way we register the ember-cp-validations preprocessor
  index.js
Labels: ready for review

#1162 octanifies search box.
  addon/components/search-box.hbs
  addon/components/search-box.js
  addon/components/user-search.js
Labels: ready for review

#1155 Octanify Course Objectives
  addon-test-support/ilios-common/page-objects/components/course/manage-objective-descriptors.js
  addon-test-support/ilios-common/page-objects/components/course/manage-objective-parents.js
  addon-test-support/ilios-common/page-objects/components/course/objectives.js
  addon-test-support/ilios-common/page-objects/course.js
  addon/components/course-editing.hbs
  addon/components/course-objective-list-item.hbs
  addon/components/course-objective-manager.hbs
  addon/components/course-objective-manager.js
  addon/components/course/manage-objective-descriptors.hbs
  addon/components/course/manage-objective-parents-item.hbs
  addon/components/course/manage-objective-parents.hbs
  addon/components/course/manage-objective-parents.js
  addon/components/course/objectives.hbs
  addon/components/course/objectives.js
  addon/mixins/course/index-route.js
  app/components/course-objective-manager.js
  app/components/course/manage-objective-descriptors.js
  app/components/course/manage-objective-parents-item.js
  app/components/course/manage-objective-parents.js
  app/components/course/objectives.js
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/course-objective-manager.scss
  app/styles/ilios-common/components/course/manage-objective-parents.scss
  tests/acceptance/course/competencies-test.js
  tests/acceptance/course/objectivecreate-test.js
  tests/acceptance/course/objectivemesh-test.js
  tests/acceptance/course/objectiveparents-multiplecohorts-test.js
  tests/acceptance/course/objectiveparents-nocohorts-test.js
  tests/acceptance/course/objectiveparents-test.js
  tests/integration/components/course/manage-objective-descriptors-test.js
  tests/integration/components/course/manage-objective-parents-item-test.js
  tests/integration/components/course/manage-objective-parents-test.js
  tests/integration/components/course/objectives-test.js
Labels: ready for review

#1163 Improve monthly calendar style
  addon/components/ilios-calendar-week.hbs
  addon/components/ilios-calendar.hbs
  addon/components/monthly-calendar.hbs
  app/styles/ilios-common/components.scss
  app/styles/ilios-common/components/ilios-calendar-month.scss
  app/styles/ilios-common/components/ilios-calendar.scss
  app/styles/ilios-common/components/monthly-calendar.scss
Labels: ready for review

#1171 Auto merge icon updates
  .dependabot/config.yaml
Labels: dependencies, ready for review

#1173 Octaneify Ilios Calendar Event Month
  addon/components/ilios-calendar-event-month.hbs
  addon/components/ilios-calendar-event-month.js
  addon/utils/calendar-event-tooltip.js
  app/utils/calendar-event-tooltip.js
  tests/integration/components/ilios-calendar-event-month-test.js
  tests/unit/utils/calendar-event-tooltip-test.js
Labels: ready for review

#1187 Upgrade ember-cli to v3.16.0
  .editorconfig
  LICENSE.md
  config/ember-try.js
  package-lock.json
  package.json
  testem.js
Labels: dependencies

#1188 Don't send cookies with API requests
  addon/adapters/ilios.js
Labels: enhancement

#1161 Force babel to only work with parallel builds
  ember-cli-build.js
Labels: ready for review
