Repository ilios/common, pull requests merged in 2023-10, with the labels that each got.

#3577 Fix group of percy tests
  .github/workflows/percy.yml
Labels: run percy tests

#3580 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, run percy tests

#3582 Update Ember CLI to v5.3.0
  package-lock.json
  package.json
  tests/dummy/config/ember-cli-update.json
  tests/dummy/config/ember-try.js
  tests/helpers/index.js
Labels: dependencies

#3588 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, run percy tests

#3593 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, run percy tests

#3600 Update Transitive Dependencies
  package-lock.json
Labels: dependencies, run percy tests
